# Numpy Programs

'''
@Author: Shubham shirke
@Date: 2023-06-23 12:30:30
@Last Modified by: shubham shirke
@Last Modified time: 2023-06-23 17:00:30
@Title : Python Library numpy programs
''' 


Import Libraries

In [1]:
import numpy as np

In [2]:
# Implement logging
import logging
import sys
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s',
                    handlers= [logging.FileHandler("numpy.log"),
                               logging.StreamHandler(sys.stdout)])

# Create a logger
logger = logging.getLogger(__name__)


1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [3]:


array = np.array([12.23,13.32,100,36.32])
print(array)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [4]:


matrix = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [5]:


null_vector = np.array([0,0,0,0,0,0,0,0,0,0])
null_vector[6] = 11
print(null_vector)


[ 0  0  0  0  0  0 11  0  0  0]


4. Write a Python program to reverse an array (first element becomes last).

In [6]:


array = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
reverse_array = np.flip(array)
print(f"Reversed Array: {reverse_array}")

Reversed Array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5.Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [7]:


original_array = np.ones((5,5))
print(f"Original array:\n{original_array}")
print("1 on the border and 0 inside in the array")
original_array[1:-1,1:-1] = 0
print(original_array)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [8]:

original_array = np.ones((3,3))
print(f"Original array:\n{original_array}")
print("0 on the border and 1 inside in the array")
new_array = np.pad(original_array,pad_width=1,mode='constant',constant_values=0)
print(new_array)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7.Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [9]:

array = np.zeros((8,8),dtype=int)
print(array)
print()
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8.Write a Python program to convert a list and tuple into arrays.

In [10]:
list1 = [1,2,3,4,5,6]
list_array = np.array(list1,dtype=int)
print(list_array)

tuple_1  = ([8,4,6],[1,2,3])
tuple_array = np.array(tuple_1)
print(tuple_array)

[1 2 3 4 5 6]
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.


In [11]:
import numpy as np
original_array = [10,20,30]
print(f"Original_array: {original_array}")

new_array = np.append(original_array,[[40,50,60],[70,80,90]])
print(f"New concatenated array: {new_array}")

Original_array: [10, 20, 30]
New concatenated array: [10 20 30 40 50 60 70 80 90]


10.Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [12]:
import numpy as np

Original_array = np.array([1.00000000+0.j,0.70710678+0.70710678j])
real_part = Original_array.real
print(f"Real part: {real_part}")
imaginary_part = Original_array.imag
print(f"Imaginary part: {imaginary_part}")

Real part: [1.         0.70710678]
Imaginary part: [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [13]:
import numpy as np

array = np.array([23,3,42,3,55,45,7,53,5],dtype=np.float64)
size = array.size
print(f"Size of the array: {size}")
bytes = array.itemsize
print(f"Length of one array element in bytes: {bytes}")
total_bytes = array.nbytes
print(f"Total bytes consumed by the elements: {total_bytes}")

Size of the array: 9
Length of one array element in bytes: 8
Total bytes consumed by the elements: 72


12. Write a Python program to find common values between two arrays.

In [14]:
import numpy as np
array_1 = np.array([0,10,20,40,60])
array_2 = np.array([10,30,40])
common_values = np.intersect1d(array_1,array_2)
print(f"Common values between two are: {common_values}")


Common values between two are: [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.


In [15]:
import numpy as np
import logging
try:
    array_1 = np.array([0,10,20,40,60,80])
    array_2 = np.array([10,30,40,50,70,90])
    difference = np.setdiff1d(array_1,array_2)
    print(f"The differece betweem twp arrays is: {difference}")
    logging.info("Difference succesfully found")
except Exception as e:
    logger.error(str(e))

The differece betweem twp arrays is: [ 0 20 60 80]
2023-06-26 10:58:24,375 - INFO - Difference succesfully found


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.


In [16]:
import numpy as np
try:
    Array1 = np.array([0,10,20,40,60,80])
    Array2 = np.array([10,30,40,50,70])
    Array_3 = np.setxor1d(Array1,Array2)
    print(Array_3)
    logger.info("Succesfully found unique values")
except Exception as e:
    logger.warning(str(e))

[ 0 20 30 50 60 70 80]
2023-06-26 10:58:24,392 - INFO - Succesfully found unique values


15. Write a Python program compare two arrays using numpy.


In [17]:
import numpy as np

try:
    Array_a = np.array([1,2])
    Array_b = np.array([4,5])

    result_1 = np.greater(Array_a,Array_b)
    print(result_1)
    result_2 = np.greater_equal(Array_a,Array_b)
    print(result_2)
    result_3 = np.less(Array_a,Array_b)
    print(result_3)
    result_4 = np.less_equal(Array_a,Array_b)
    print(result_4)
    logger.info("Succesfully compared")
except Exception as e:
    logger.warning(str(e))


[False False]
[False False]
[ True  True]
[ True  True]
2023-06-26 10:58:24,407 - INFO - Succesfully compared


16.Write a Python program to save a NumPy array to a text file.

In [18]:
import numpy as np
from numpy import savetxt 
try:
    array_for_file = np.arange(1,11) # create a array from 1 to 10
    print(array_for_file)
    # save to txt file as full precision
    savetxt('numpy.txt',array_for_file,delimiter=',')
    logger.info("Array successfully added to file")
except Exception as e:
    logger.error(str(e))
    


[ 1  2  3  4  5  6  7  8  9 10]
2023-06-26 10:58:24,429 - INFO - Array successfully added to file


17. Write a Python program to create a contiguous flattened array.


In [19]:
import numpy as np
try:
    array = np.array([[10,20,30],[20,40,50]])
    # reduce the dimentionality
    flatten_array = np.ndarray.flatten(array)
    print(flatten_array)
    logger.info("array collapsed to single dimension")
except Exception as e:
    logger.warning(str(e))

[10 20 30 20 40 50]
2023-06-26 10:58:24,454 - INFO - array collapsed to single dimension


18. Write a Python program to change the data type of an array.


In [20]:
import numpy as np

try:
    int_array = np.array([[ 2, 4, 6],[ 6, 8, 10]])
    print(f"Data type of the array is: {int_array.dtype}")
    # convert to float data type using astype
    float_array = int_array.astype('float64')
    print(f"New type: {float_array.dtype}\n{float_array}")
    logger.info("Array data type succesfully converted")

except Exception as e:
    logger.warning(str(e))

Data type of the array is: int32
New type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
2023-06-26 10:58:24,470 - INFO - Array data type succesfully converted


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.


In [21]:
import numpy as np

try:
    diagonal_array = np.eye(3,3)
    print(diagonal_array)
    logger.info("succssfully 3-D array with ones on a diagonal and zeros elsewhere created")
except Exception as e:
    logger.warning(str(e))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2023-06-26 10:58:24,484 - INFO - succssfully 3-D array with ones on a diagonal and zeros elsewhere created


20. Write a Python program to create an array which looks like below array.

In [32]:
import numpy as np
try:
    # create triangular matrix with dimension 4X3
    pattern = np.tri(4,3,-1)
    print(pattern)
    logger.info("Triangular pattern succesfully created")
except Exception as e:
    logger.error(str(e))


2023-06-26 11:20:35,111 - ERROR - tri() missing 1 required positional argument: 'N'


21. Write a Python program to concatenate two 2-dimensional arrays.

In [23]:
import numpy as np

try:
    list1 = [[0, 1, 3], [5, 7, 9]]
    list2 = [[0, 2, 4], [6, 8, 10]]
    array1 = np.array(list1)
    array2 = np.array(list2)
    # concatenate two list
    concat_array = np.concatenate((array1,array2),axis=1)
    print(concat_array)
    logger.info("2-Dimentional concetenated sucessfully")

except Exception as e:
    logger.error(str(e))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
2023-06-26 10:58:24,532 - INFO - 2-Dimentional concetenated sucessfully


22. Write a Python program to make an array immutable (read-only).

In [24]:
import numpy as np

try:
    array = np.arange(1,11)
    print(array)

    # Make the array read-only
    array.flags.writeable = False

    # Try to modify the array
    array[0] = 10
    
except Exception as e:
    logger.error(str(e))

[ 1  2  3  4  5  6  7  8  9 10]
2023-06-26 10:58:24,547 - ERROR - assignment destination is read-only


23. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.


In [25]:
import numpy as np

try:
    # Create a 1D array of values from 0 to 11
    arr_1d = np.arange(12)

    # Reshape the 1D array to a 3x4 matrix
    arr_2d = arr_1d.reshape(3, 4)

    multiplication_array = arr_2d*3

    print(multiplication_array)
    logger.info("Successfully executed")

except Exception as e:
    logger.error(str(e))

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
2023-06-26 10:58:24,566 - INFO - Successfully executed


24. Write a Python program to convert a NumPy array into Python list structure.


In [26]:
import numpy as np

try:
    print("Array:")
    array = np.array([[0,1],[2,3],[4,5]])
    print(array)
    # convert array to list
    array_list = array.tolist()
    print("Array to list is: ")
    print(array_list)
    logger.info("Suceesfully array converted to list")
except Exception as e:
    logger.error(str(e))


Array:
[[0 1]
 [2 3]
 [4 5]]
Array to list is: 
[[0, 1], [2, 3], [4, 5]]
2023-06-26 10:58:24,580 - INFO - Suceesfully array converted to list


25. Write a Python program to convert a NumPy array into Python list structure with precision 3.

In [27]:
import numpy as np

try:
    array = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
    # round with precision 3
    list_arr = np.round(array,3).tolist()

    print(f"List values with precision 3 :{list_arr}")
    logger.info("Successfully converted array to list with precision 3")

except Exception as e:
    logger.error(str(e))

List values with precision 3 :[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]
2023-06-26 10:58:24,596 - INFO - Successfully converted array to list with precision 3


26. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array.


In [28]:
try:
    original_array = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
    np.set_printoptions(suppress=True,precision=3)
    print(f"New array: {Original_array}")
    logger.info("Succesfully printed scientific notation for small numbers with precision 3")

except Exception as e:
    logger.error(str(e))

New array: [1.   +0.j    0.707+0.707j]
2023-06-26 10:58:24,611 - INFO - Succesfully printed scientific notation for small numbers with precision 3


27. Write a Python program to how to add an extra column to an numpy array.

In [29]:
import numpy as np

try:
    arr = np.array([[1, 2], [3, 4], [5, 6]])

    extra_col = np.array([7, 8, 9])

    # adding extra column to the original array using numpy.concatenate() function
    arr_with_extra_col = np.concatenate((arr, extra_col.reshape(-1, 1)), axis=1)

    print("Original array:")
    print(arr)
    print("Array with extra column:")
    print(arr_with_extra_col)
    logger.info("Successfully column added to array")
except Exception as e:
    logger.error(str(e))


Original array:
[[1 2]
 [3 4]
 [5 6]]
Array with extra column:
[[1 2 7]
 [3 4 8]
 [5 6 9]]
2023-06-26 10:58:24,627 - INFO - Successfully column added to array


28. Write a Python program to remove specific elements in a numpy array.


In [30]:
import numpy as np

try:
    array = np.arange(0,10)
    print(f"Original array: {array}")
    element = [5,6,7]
    # delete elements from array.
    new_array = np.delete(array,element)
    print(f"Array after deletion: {new_array}")

except Exception as e:
    logger.error(str(e))


Original array: [0 1 2 3 4 5 6 7 8 9]
Array after deletion: [0 1 2 3 4 8 9]
